<TR>
		<TD vAlign="middle" align="left" height="20">
				<table cellSpacing="0" cellPadding="0" border="0" width="100%">
						<tr height="20" style="BACKGROUND-IMAGE: url(img/lowerbar.jpg); COLOR: #444444; BACKGROUND-REPEAT: repeat">
								<td align="left">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Punjab State Power Corporation Ltd</td>
								<td align="right"><a style="FONT-WEIGHT: normal;BACKGROUND-IMAGE: url(img/lowerbar.jpg); COLOR: #444444;" >Powered by O/o SE/IT PSPCL Patiala</a>&nbsp;</td>
						</tr>
				</table>
		</TD>
</TR>
